In [ ]:
# 1d 2d 3d
# special arrays
# attributes
# indexing
# slicing
# performance
# vector operation
# reshaping
# aggregate
# stacking 
# splitting

# numpy
# numerical python
# array 
# faster bcoz it uses c
# mathematical operation
# it saves the memory

import numpy as np



In [181]:
import numpy as np

# 1d array
arr1=np.array([1,2,3])
arr1
# 2d array
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2
# 3d array
arr3=np.array([
    [[1,2],[3,4],[5,6]],
    [[7,8],[9,10],[11,12]]
])
arr3

# special arrays
# np.zeros((2,3,2))
# np.eye(4)
# np.ones((2,3))
# np.full((2,3),7)
# np.arange(10,100,2)
# np.linspace(1,100,10)

# indexing
# print(arr2)
#fancy indexing
# arr2[[0,2]]

# # slicing
# print(arr3)
# arr3[0:1,::-1,::-1]

# attributes
arr2.ndim
arr2.size
arr2.dtype
arr2.shape

# vector operations + -* / **
# print(arr3)

# # reshaping
# print(arr3.size)
# print(arr3.reshape(6,2))

# aggregrating funcions
# sum min max mean 
# print(arr2)
arr2.mean()


# stacking -adding two arrays - horizontal or vertical
print(arr2)
# print(np.hstack((arr2,arr2)))
# print(np.vstack((arr2,arr2)))

# splitting-dividing the array
print(np.split(arr2,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [136]:
import time

arr=np.arange(1000000)

a=time.time()
arr.sum()
print(time.time()-a)

li=list(range(1000000))

a=time.time()
sum(li)
print(time.time()-a)

0.0010013580322265625
0.02804708480834961
