In [43]:
import numpy as np

In [68]:


# # # splitting
# # arr=np.arange(1,10)
# # np.split(arr,3)[0]

# # # broad casting - performing an operation on each elemnt
# # arr=np.array([[1,2,3],[4,5,6]])
# # print(arr+5)
# # print(arr-5)
# # print(arr/5)
# # print(arr*5)

# # filtering
# arr=np.arange(1,10)
# print(arr>5)

# # boolean indexing
# print(arr[arr>5])
arr=np.arange(1,10)

# conditioning in numpy
# np.where(condition, ifstatement,elsestatement)
# np.where(arr%2==0, "even","odd")

# to generate random numbers
np.random.rand(5)
# to generate random single integer
np.random.randint(1,100)
# to generate random multiple integer
np.random.randint(1,100,size=10)
# to generate random multiple integer in a 1d ,2d or 3d format
np.random.randint(1,100,size=(3,3))
# to change the by default algo value- it can generate same random thing everytim
np.random.seed(8)
np.random.randint(1,100)


68

In [84]:
# matrix

a=np.array([
    [1,2],
    [3,4]
])
b=np.array([
    [5,6],
    [7,8]
])
# how to add two matrix
print(a+b)
# how to subtract
print(a-b)
# how to multiply
print(a*b)
# how to calculate the dot matrix
np.dot(a,b)
print(a @ b)


np.linalg.det(b)
np.linalg.inv(b)
np.linalg.trace(a)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


np.int64(5)